### ISSUE TITLE
Feature Request: War Graph

### ISSUE THREAD

**Issue by CharonM72** [Kromtec/Legends-Viewer#13]
Legends Browser has a really badass hoverable war graph. Can some kind of war graph be implemented in Legends Viewer? It would make it a lot easier to see who was the most aggressive, and who attacked who, etc.

**Comment by leacasas** [comment]
I think this can be accomplished using [vis.js](http://visjs.org/). I can try to do a Proof of Concept to see if it works.

**Comment by Kromtec** [comment]
I already use Cytoscape.js for the familytrees. Would be cool if you could try to make the war graph with the same library. But if another tool is better suited feel free to include it.

**Comment by leacasas** [comment]
@Kromtec  I've finished a proof of concept, if you want to check it out. It is just an overview of the wars. A couple of charts that show attack/defend statistics plus a circular graph that shows more visually who attacked who. I put it on the world stats, but if it works I could develop a more fleshed out version and include it in the warfare tab.

**Comment by Kromtec** [comment]
@leacasas 
I like it. This will be really cool!

Feedback:
[Wars by Civ](http://i.imgur.com/h36XNPU.png)
"Wars fought by Civilization" should be grouped by civilizations. Currently it shows a bar for each entity, which can get very cluttered real fast. 
The entity class has the properties Entity.IsCiv and Entity.Parent. Every entity that has no parent and is not a civ (like nomads, outcasts, ...) could be grouped into an independent group.
>:exclamation: _I am not sure if entities that are part of a civ are always a direct child of the civ. Maybe you have to go from parent to parent until it is null or a Civ._

You could make a more detailed chart on the entity page of civilizations that shows all wars of child entites of this civ.

[War Graph](http://i.imgur.com/Fvlyxn6.png)
Same issue here. Try to group by civ and find a style that grants a good readablity for medium sized worlds with medium history.

**Comment by leacasas** [comment]
Thanks for your feedback, I really appreciate it.

The past few days I haven't been available to take a look at this, maybe in a few days I'll be able to review this once again.

I had issues with DF in my machine to generate large worlds with long history, I guess I'll ask in forums for big saves in order to get a good set of test data. I wasn't able to test this with more than 20 civs (and strangely enough almost always the goblins were the absolute masters of the world).

Another thing to point out is that the circle layout of Cytoscape.js is not very flexible (at least I haven found a way to really manipulate the sizes and all that)

**Comment by Kromtec** [comment]
Implemented in version 1.18.00
