### ISSUE TITLE
Civilization pop increase after subsequent legends downloads

### ISSUE THREAD

**Issue by jordanCu** [Kromtec/Legends-Viewer#36]
Every time I export legends and then open the in legends viewer the population of dwarves has increased. Most recently it is at 225 million.  44.09 and Viewer 1.19.08.

**Comment by Kromtec** [comment]
Hm, I can not reproduce your problem.

Can you look into the file `regionx-xxxxx-xx-xx-world_sites_and_pops.txt`, right at the top there should be the Civilized World Population list. If the values there match what is displayed in the Legends Viewer, then the issue lies in DF or DFHack where you exported the files. If the values are not equal, please describe the exact steps you took. 

- Did you use DF or DFHack to export the files?
- Did you play between the exports? 
- Did you close Legends Viewer between the imports?
- ...

**Comment by jordanCu** [comment]
The values match! Thanks for the quick response.

BTW legends viewer is fantastic and I can't imagine playing DF without it.
Thanks for creating/improving/maintaining it.
