### ISSUE TITLE
Duplicate Site Government Names Potentially Messing With Site Ownership

### ISSUE THREAD

**Issue by zackman0010** [Kromtec/Legends-Viewer#37]
I have a save in which there are two entirely separate human civilizations on opposite ends of the map. However, these two civilizations both have a site government with the same name. For some reason, this has caused some problems with the site ownership of the cities owned by that site government. Legends Viewer says that both cities are owned by both civilizations at once. This leads to some visual errors on the world map.
I have a much better bug report prepared along with the save file and the export data (exported with DFHack), but I'm in a place with bad Internet at the moment. I will upload that and share a link here when I have better Internet. Until then, I made a much more basic report in Paint: https://imgur.com/a/OuUqiwH
Disclaimer: Yes, I am using Masterwork, and yes, I know that it's buggy. However, I do not believe this problem is related to Masterwork. I explored through the legends.xml file myself, and I found no link between the site government of the second civ and the city.

**Comment by Kromtec** [comment]
Current site ownership is not based on the xml but on the information from the `regionx-xxxxx-xx-xx-world_sites_and_pops.txt` file. The owner is unfortunately only mentioned by name and not by ID in this file, which can lead to such (rare) cases. This file is sadly the single source where I can get this information, because the xml only includes information about some events when sites are founded, destroyed and so on but nothing reliable about the current owner.

**Comment by Kromtec** [comment]
Can you provide the exported files? I will try to improve this part of the code.
_regionx-xxxxx-xx-xx-legends.xml
regionx-xxxxx-xx-xx-legends_plus.xml
regionx-xxxxx-xx-xx-world_history.txt
regionx-xxxxx-xx-xx-world_map.bmp
regionx-xxxxx-xx-xx-world_sites_and_pops.txt_

**Comment by Kromtec** [comment]
Thanks and special thanks for even including the line numbers! :+1:

**Comment by Kromtec** [comment]
improvements made in v1.19.09
